---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: 2gis-audiogid-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30778
        hostPort: 9001
      - containerPort: 30101
        hostPort: 30101
      - containerPort: 30102
        hostPort: 30102
      - containerPort: 30103
        hostPort: 30103
  - role: worker
  - role: worker
  - role: worker
  - role: worker
